### ISSUE TITLE
Guidance for regex codes to get status

### ISSUE THREAD

**Issue by seanwalter** [iSteve-O/homebridge-multiswitcheroo#4]
After a lot of trial and error, it appears that spaces in the Status Pattern regex field need to be escaped. I created a switch that in its on state should get back a status pattern of `200` followed by a space and then a number between `0` and `100`.

A standard regex for that would be `200 [0-9]+` but this resulted in the switch reverting to the off state immediately after being turned on. I eventually thought to try `200\ [0-9]+` and that works reliably.

I recommend that in the Readme or in the instructions within the UI itself you make it clear that the Status Pattern requires that certain characters be escaped. It's somewhat implied in the example conf that certain characters need to be escaped, but because the double quotes in the example regex are nested within the double quotes of the json, it's "obvious" that you would need to escape those. Given the double quotes are the only special characters that are escaped in the example, it's less obvious that you would also need to escape other characters.

**Comment by iSteve-O** [comment]
@seanwalter you are probably correct. I should put it under the box where it is entered in the configUI plugin settings as well as in the readme. 

I’ll write something like “remember to escape special characters, including spaces, with a \ before them”. 

In all honesty, I thought the configUI took care of all of the escaping if you just put the text string into the plugin settings box, but I tried with your example and it did not. I may need to change the type of that settings box in the config.schema from “string” to “regex” to make it escape a string automatically. 

I’ll play with that in the config.schema as well, but I would value your opinion on the verbiage of the escape warning. You have a good point and I apologize for the wasted time.

**Comment by iSteve-O** [comment]
I added some language to the readme to spell out the need to escape special characters (including spaces) with a `/`. Hopefully this is a good solution.
