### ISSUE TITLE
Reporting error despite getting a 204 code 

### ISSUE THREAD

**Issue by Nepomucene** [iSteve-O/homebridge-multiswitcheroo#5]
I’m using successfully this plugin to turn on/off my bike alarm.

The status GET works great. 
The switch on/off works perfectly. 

Only issue is that HomeBridge reports it as an error.

Is it possible to process the return code to say success/failure?
![IMG_3203](https://github.com/iSteve-O/homebridge-multiswitcheroo/assets/29494046/5649d92e-e84a-4352-aa0b-d57ba71b7382)

**Comment by iSteve-O** [comment]
I just published version 3.0.3 to address this issue. Let me know if any other problems. For now I will close this issue.
